server:
  port: 40080
  
# dubbo
spring:
  dubbo:
    application:
      name: registry-service-provider
    registry:
      address: zookeeper://139.196.158.120:22181
    protocol:
      name: dubbo
      port: 20880
    scan: edu.storage.service.impl